# -*- coding: utf-8 -*-
"""Catboost_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZ7fJALhcokGevTKhH5NQF5kwtjJ8E30
"""

import streamlit as st
import pandas as pd
import joblib

# Load the trained model
model = joblib.load('catboost_model.pkl')

# Load expected feature names
expected_features = joblib.load('model_features.pkl')

st.set_page_config(page_title="Online Purchase Prediction", page_icon="🛒")
st.title("🛍️ Predict Online Purchase Intention")

st.markdown("Upload your CSV file containing user behavior data:")

uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    # 🧼 Optional: Preview uploaded data
    st.subheader("📄 Uploaded Data Preview")
    st.write(df.head())

    # 💡 Perform same preprocessing here as during training
    # You MUST do one-hot encoding, imputation, scaling, etc., if used during training
    df_encoded = pd.get_dummies(df)  # Simple one-hot example

    # Align features to match the model's expected input
    df_encoded = df_encoded.reindex(columns=expected_features, fill_value=0)

    # Make predictions
    predictions = model.predict(df_encoded)

    # 🧾 Output predictions
    st.subheader("🔍 Predictions:")
    for i, pred in enumerate(predictions):
        st.write(f"Row {i + 1}: {'🟢 Will Purchase' if pred == 1 else '🔴 Will Not Purchase'}")

else:
    st.info("Please upload a CSV file to get predictions.")